apiVersion: apps/v1
kind: Deployment
metadata:
  name: pg-db
  labels:
    app: pg-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pg-db
  template:
    metadata:
      name: pg-db
      labels:
        app: pg-db
    spec:
      containers:
        - name: pg-db
          image: "sosedoff/pgweb"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
      restartPolicy: Always
